/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CI.CD.demo;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        System.out.println("You did it!");
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
